name: Update commit.txt

on:
  push:
    branches:
      - main
    paths:
      - 'livery.json'
      - 'liveries/**'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Write latest commit hash
        run: |
          # 用触发这次 workflow 的 commit hash
          echo "${{ github.sha }}" | cut -c1-40 > commit.txt
          cat commit.txt

      - name: Commit and push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add commit.txt
          git diff --cached --quiet && echo "No change" && exit 0
          git commit -m "chore: update commit.txt [skip ci]"
          git push
